dist: xenial
sudo: required
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - patch
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - pigz
      - pv

install:

## Dependencies

#- sudo apt-get install -yqqq gcc-4.4

#- sudo apt-get install -yqqq patch wget make git libc6-dev zlib1g zlib1g-dev libucl1 libucl-dev pigz pv
#- sudo apt-get install -yqqq texinfo libmpc-dev libmpfr-dev libgmp-dev
#gcc g++ 

before_script:
- export PS2DEV=~/ps2dev
- export PS2SDK=${PS2DEV}/ps2sdk
- export PATH=${PATH}:${PS2DEV}/bin:${PS2DEV}/ee/bin:${PS2DEV}/iop/bin:${PS2DEV}/dvp/bin:${PS2SDK}/bin
- echo $(nproc)
#- export PS2DEVUJ=${PS2DEV}
#- export PS2SDKUJ=${PS2SDK}
# Link gcc-7 and g++-7 to their standard commands
- sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
- sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
# Export CC and CXX to tell cmake which compiler to use
- export CC=/usr/bin/gcc-7
- export CXX=/usr/bin/g++-7
# Check versions of gcc, g++ and cmake
- gcc -v && g++ -v && cmake --version
# Run your build commands next
script:

# - travis_wait 60 bash ./toolchain.sh > /tmp/PS2TOOLCHAIN.log 2>&1

# - curl --upload-file /tmp/PS2TOOLCHAIN.log https://transfer.sh/PS2TOOLCHAIN${TRAVIS_BUILD_NUMBER}.log

- bash ./toolchain.sh 1
- bash ./toolchain.sh 2
- bash ./toolchain.sh 3
- bash ./toolchain.sh 4
- bash ./toolchain.sh 5
- bash ./toolchain.sh 6
- bash ./toolchain.sh 7
