dist: xenial
  addons:
    apt:
      packages:
        - texinfo patch wget make git 
        - libc6-dev zlib1g zlib1g-dev libucl1 libucl-dev
        - libmpc-dev libmpfr-dev libgmp-dev
        - pigz pv
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

sudo: required
language: cpp

before_install:
    - eval "${MATRIX_EVAL}"

install:
## Dependencies
#- sudo apt-get install -yqqq gcc-4.4
#- sudo apt-get install -yqqq patch wget make git libc6-dev zlib1g zlib1g-dev libucl1 libucl-dev pigz pv
#- sudo apt-get install -yqqq texinfo libmpc-dev libmpfr-dev libgmp-dev
#gcc g++ 
before_script:
- export PS2DEV=~/ps2dev
- export PS2SDK=${PS2DEV}/ps2sdk
- export PATH=${PATH}:${PS2DEV}/bin:${PS2DEV}/ee/bin:${PS2DEV}/iop/bin:${PS2DEV}/dvp/bin:${PS2SDK}/bin
- echo $(nproc)
#- export PS2DEVUJ=${PS2DEV}
#- export PS2SDKUJ=${PS2SDK}
# Check versions of gcc, g++ and cmake
- gcc -v && g++ -v
# Run your build commands next
script:
# - travis_wait 60 bash ./toolchain.sh > /tmp/PS2TOOLCHAIN.log 2>&1
# - curl --upload-file /tmp/PS2TOOLCHAIN.log https://transfer.sh/PS2TOOLCHAIN${TRAVIS_BUILD_NUMBER}.log
- bash ./toolchain.sh 1
- bash ./toolchain.sh 2
- travis_wait 50 bash ./toolchain.sh 3
- bash ./toolchain.sh 4
- travis_wait 50 bash ./toolchain.sh 5
- bash ./toolchain.sh 6
- bash ./toolchain.sh 7
